version: "2"

services:
  mysqldb:
    image: mysql:8-oracle

    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=hobbie_backend_db 
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10      

  spring-backend:
    image: spring-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/hobbie_backend_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Europe/Paris
    networks:
      - springmysql-net
    depends_on:
      mysqldb:
        condition: service_healthy

networks:
  springmysql-net: